import { googleSearchActions, imageGroupActions } from '../actions/models';

export const BASE = 'http://localhost:8000';
export const API = 'http://localhost:8000/api/v1';
export const STATIC = `${BASE}/static`;
export const ACCESS_TOKEN = 'auth_token';
export const REFRESH_TOKEN = 'refresh_token';
export const REFRESH_TOKEN_EXPIRATION = 'refresh_token_expiration';
export const DATE_FORMAT = 'LLL dd, yyyy';

const TYPES = {
  // global actions
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SET_HEADER_TEXT: 'SET_HEADER_TEXT',
  CLEAR_HEADER_TEXT: 'CLEAR_HEADER_TEXT',
  CHECK_STATUS: 'CHECK_STATUS',
  CHECK_STATUS_SUCCESS: 'CHECK_STATUS_SUCCESS',
  CHECK_STATUS_FAILURE: 'CHECK_STATUS_FAILURE',
  RESET_LAST_CREATED_ID: 'RESET_LAST_CREATED_ID',

  // display
  SHOW_TRANSITION_LOADER: 'SHOW_TRANSITION_LOADER',
  HIDE_TRANSITION_LOADER: 'HIDE_TRANSITION_LOADER',

  // authentication
  GET_AUTH_TOKEN: 'GET_AUTH_TOKEN',
  GET_AUTH_TOKEN_SUCCESS: 'GET_AUTH_TOKEN_SUCCESS',
  GET_AUTH_TOKEN_FAILURE: 'GET_AUTH_TOKEN_FAILURE',
  REFRESH_AUTH_TOKEN: 'REFRESH_AUTH_TOKEN',
  REFRESH_AUTH_TOKEN_SUCCESS: 'REFRESH_AUTH_TOKEN_SUCCESS',
  REFRESH_AUTH_TOKEN_FAILURE: 'REFRESH_AUTH_TOKEN_FAILURE',
  CLEAR_AUTH_TOKEN: 'CLEAR_AUTH_TOKEN',
  REHYDRATE_AUTH_TOKEN: 'REHYDRATE_AUTH_TOKEN',

  // websockets
  WEBSOCKET_INITIALIZE: 'WEBSOCKET_INITIALIZE',
  WEBSOCKET_INITIALIZE_SUCCESS: 'WEBSOCKET_INITIALIZE_SUCCESS',
  WEBSOCKET_INITIALIZE_FAILURE: 'WEBSOCKET_INITIALIZE_FAILURE',
  WEBSOCKET_POST_ERROR: 'WEBSOCKET_POST_ERROR',
  WEBSOCKET_GENERIC_ERROR: 'WEBSOCKET_GENERIC_ERROR',
  WEBSOCKET_CLOSED: 'WEBSOCKET_CLOSED',

  WEBSOCKET_ASYNC_INITIALIZE: 'WEBSOCKET_ASYNC_INITIALIZE',
  WEBSOCKET_ASYNC_INITIALIZE_SUCCESS: 'WEBSOCKET_ASYNC_INITIALIZE_SUCCESS',
  WEBSOCKET_ASYNC_INITIALIZE_FAILURE: 'WEBSOCKET_ASYNC_INITIALIZE_FAILURE',
  WEBSOCKET_ASYNC_POST_ERROR: 'WEBSOCKET_ASYNC_POST_ERROR',
  WEBSOCKET_ASYNC_GENERIC_ERROR: 'WEBSOCKET_ASYNC_GENERIC_ERROR',
  WEBSOCKET_ASYNC_CLOSED: 'WEBSOCKET_ASYNC_CLOSED',

  // modal actions
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  TOGGLE_IMAGE_INCLUDED: 'TOGGLE_IMAGE_INCLUDED',
  TOGGLE_IMAGE_INCLUDED_SUCCESS: 'TOGGLE_IMAGE_INCLUDED_SUCCESS',
  TOGGLE_IMAGE_INCLUDED_FAILURE: 'TOGGLE_IMAGE_INCLUDED_FAILURE',

  SET_ACTIVE_CLASSIFIER: 'SET_ACTIVE_CLASSIFIER',
  FETCH_CLASSIFIER: 'FETCH_CLASSIFIER',
  FETCH_CLASSIFIER_SUCCESS: 'FETCH_CLASSIFIER_SUCCESS',
  FETCH_CLASSIFIER_FAILURE: 'FETCH_CLASSIFIER_FAILURE',
  FETCH_CLASSIFIERS: 'FETCH_CLASSIFIERS',
  FETCH_CLASSIFIERS_SUCCESS: 'FETCH_CLASSIFIERS_SUCCESS',
  FETCH_CLASSIFIERS_FAILURE: 'FETCH_CLASSIFIERS_FAILURE',
  CREATE_CLASSIFIER: 'CREATE_CLASSIFIER',
  CREATE_CLASSIFIER_SUCCESS: 'CREATE_CLASSIFIER_SUCCESS',
  CREATE_CLASSIFIER_FAILURE: 'CREATE_CLASSIFIER_FAILURE',
  UPDATE_CLASSIFIER: 'UPDATE_CLASSIFIER',
  UPDATE_CLASSIFIER_SUCCESS: 'UPDATE_CLASSIFIER_SUCCESS',
  UPDATE_CLASSIFIER_FAILURE: 'UPDATE_CLASSIFIER_FAILURE',
  DELETE_CLASSIFIER: 'DELETE_CLASSIFIER',
  DELETE_CLASSIFIER_SUCCESS: 'DELETE_CLASSIFIER_SUCCESS',
  DELETE_CLASSIFIER_FAILURE: 'DELETE_CLASSIFIER_FAILURE',

  googleSearch: googleSearchActions.types,
  MERGE_GOOGLE_SEARCHES: 'MERGE_GOOGLE_SEARCHES',
  MERGE_GOOGLE_SEARCHES_SUCCESS: 'MERGE_GOOGLE_SEARCHES_SUCCESS',
  MERGE_GOOGLE_SEARCHES_FAILURE: 'MERGE_GOOGLE_SEARCHES_FAILURE',
  RESET_GOOGLE_SEARCH_WEBSOCKET_LOG: 'RESET_GOOGLE_SEARCH_WEBSOCKET_LOG',
  UPDATE_GOOGLE_SEARCH_LOG: 'UPDATE_GOOGLE_SEARCH_LOG',
  CREATE_GOOGLE_SEARCH_COMPLETE: 'CREATE_GOOGLE_SEARCH_COMPLETE',
  CREATE_GOOGLE_SEARCH_FAILURE: 'CREATE_GOOGLE_SEARCH_FAILURE',

  MERGE_UPLOAD_EVENTS: 'MERGE_UPLOAD_EVENTS',
  MERGE_UPLOAD_EVENTS_SUCCESS: 'MERGE_UPLOAD_EVENTS_SUCCESS',
  MERGE_UPLOAD_EVENTS_FAILURE: 'MERGE_UPLOAD_EVENTS_FAILURE',

  imageGroups: imageGroupActions.types,
};

export default TYPES;
