# Generated by Django 2.0.3 on 2018-07-01 18:18

import os
import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.auth import get_user_model


def forwards_func(apps, schema_editor):
    User = get_user_model()
    try:
        user_name = os.environ['DJANGO_ADMIN_USER']
        user_password = os.environ['DJANGO_ADMIN_PASSWORD']
    except KeyError:
        return

    User.objects.create_superuser(user_name, 'test@test.com', user_password)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_image_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['png', 'jpeg', 'jpg'], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_unavailable', models.BooleanField(default=False)),
                ('throw_api_400s', models.BooleanField(default=False)),
                ('throw_api_500s', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
