apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
  selector:
    service: redis

