# Generated by Django 2.0.3 on 2018-06-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='image_groups',
            field=models.ManyToManyField(blank=True, to='images.ImageGroup'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='transforms',
            field=models.ManyToManyField(to='api.Transform'),
        ),
    ]
