# Generated by Django 2.0.3 on 2018-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180525_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
