# Generated by Django 2.0.3 on 2018-05-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180526_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrecord',
            name='slug',
        ),
    ]
