# Generated by Django 2.0.3 on 2018-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='file_name',
            field=models.CharField(default='test.zip', max_length=255),
            preserve_default=False,
        ),
    ]
