# Generated by Django 2.0.3 on 2018-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_uploadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
