# Generated by Django 2.0.3 on 2018-05-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
