# Generated by Django 2.0.3 on 2018-05-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20180527_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uuid',
        ),
    ]
