apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: rabbit
  name: rabbit
spec:
  type: ClusterIP
  ports:
  - name: rabbit
    port: 5672
  - name: rabbit-admin
    port: 15672
  selector:
    service: rabbit

