
INITIALIZE_WEBSOCKET_SUCCESS = 'INITIALIZE_WEBSOCKET_SUCCESS'
GENERIC_WEBSOCKET_ERROR = 'GENERIC_WEBSOCKET_ERROR'
INVALID_ACTION_ERROR = 'INVALID_ACTION_ERROR'
ACTION_RESPONSE_ERROR = 'ACTION_RESPONSE_ERROR'
UNAUTHENTICATED_USER_ERROR = 'UNAUTHENTICATED_USER_ERROR'

CREATE_GOOGLE_SEARCH = 'CREATE_GOOGLE_SEARCH'
UPDATE_GOOGLE_SEARCH_LOG = 'UPDATE_GOOGLE_SEARCH_LOG'
CREATE_GOOGLE_SEARCH_SUCCESS = 'CREATE_GOOGLE_SEARCH_SUCCESS'
CREATE_GOOGLE_SEARCH_COMPLETE = 'CREATE_GOOGLE_SEARCH_COMPLETE'
CREATE_GOOGLE_SEARCH_FAILURE = 'CREATE_GOOGLE_SEARCH_FAILURE'

